package com.matas.liteconstruct.ignite.model;

import java.util.UUID;
import lombok.Getter;
import lombok.Setter;

/**
 * ClassAccessRule definition.
 * 
 * This file was generated by Ignite Web Console (11/29/2019, 10:36)
 **/
public class ClassAccessRule implements AccessRuleAbstract/* implements Serializable */ {
  /** */
  // private static final long serialVersionUID = 0L;
  private UUID id;

  /** Value for name. */
  private String name;

  /** Value for companyId. */
  private UUID companyId;

  /** Value for classId. */
  private UUID classId;

  /** Value for accessFilterGroupId. */
  private UUID accessFilterGroupId;

  /** Value for editAccess. */
  private short editAccess;

  /** Value for priority. */
  private int priority;

  /** Value for levelAccess. */
  private short levelAccess;

  /** Value for levelValue. */
  private UUID levelValue;

  /** Empty constructor. **/
  public ClassAccessRule() {
    // No-op.
  }

  /** Full constructor. **/
  public ClassAccessRule(UUID id, String name, UUID companyId, UUID classId,
      UUID accessFilterGroupId, short editAccess, int priority, short levelAccess,
      UUID levelValue) {
    this.id = id;
    this.name = name;
    this.companyId = companyId;
    this.classId = classId;
    this.accessFilterGroupId = accessFilterGroupId;
    this.editAccess = editAccess;
    this.priority = priority;
    this.levelAccess = levelAccess;
    this.levelValue = levelValue;
  }
  
  public UUID getId() {
    return id;
  }
  
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   * Gets name
   * 
   * @return Value for name.
   **/
  public String getName() {
    return name;
  }

  /**
   * Sets name
   * 
   * @param name New value for name.
   **/
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Gets companyId
   * 
   * @return Value for companyId.
   **/
  public UUID getCompanyId() {
    return companyId;
  }

  /**
   * Sets companyId
   * 
   * @param companyId New value for companyId.
   **/
  public void setCompanyId(UUID companyId) {
    this.companyId = companyId;
  }

  /**
   * Gets classId
   * 
   * @return Value for classId.
   **/
  public UUID getClassId() {
    return classId;
  }

  /**
   * Sets classId
   * 
   * @param classId New value for classId.
   **/
  public void setClassId(UUID classId) {
    this.classId = classId;
  }

  /**
   * Gets accessFilterGroupId
   * 
   * @return Value for accessFilterGroupId.
   **/
  public UUID getAccessFilterGroupId() {
    return accessFilterGroupId;
  }

  /**
   * Sets accessFilterGroupId
   * 
   * @param accessFilterGroupId New value for accessFilterGroupId.
   **/
  public void setAccessFilterGroupId(UUID accessFilterGroupId) {
    this.accessFilterGroupId = accessFilterGroupId;
  }

  /**
   * Gets editAccess
   * 
   * @return Value for editAccess.
   **/
  public short getEditAccess() {
    return editAccess;
  }

  /**
   * Sets editAccess
   * 
   * @param editAccess New value for editAccess.
   **/
  public void setEditAccess(short editAccess) {
    this.editAccess = editAccess;
  }

  /**
   * Gets priority
   * 
   * @return Value for priority.
   **/
  public int getPriority() {
    return priority;
  }

  /**
   * Sets priority
   * 
   * @param priority New value for priority.
   **/
  public void setPriority(int priority) {
    this.priority = priority;
  }

  /**
   * Gets levelAccess
   * 
   * @return Value for levelAccess.
   **/
  public short getLevelAccess() {
    return levelAccess;
  }

  /**
   * Sets levelAccess
   * 
   * @param levelAccess New value for levelAccess.
   **/
  public void setLevelAccess(short levelAccess) {
    this.levelAccess = levelAccess;
  }

  /**
   * Gets levelValue
   * 
   * @return Value for levelValue.
   **/
  public UUID getLevelValue() {
    return levelValue;
  }

  /**
   * Sets levelValue
   * 
   * @param levelValue New value for levelValue.
   **/
  public void setLevelValue(UUID levelValue) {
    this.levelValue = levelValue;
  }

  /** {@inheritDoc} **/
  @Override
  public boolean equals(Object o) {
    if (this == o)
      return true;

    if (!(o instanceof ClassAccessRule))
      return false;

    ClassAccessRule that = (ClassAccessRule) o;

    if (name != null ? !name.equals(that.name) : that.name != null)
      return false;


    if (companyId != null ? !companyId.equals(that.companyId) : that.companyId != null)
      return false;


    if (classId != null ? !classId.equals(that.classId) : that.classId != null)
      return false;


    if (accessFilterGroupId != null ? !accessFilterGroupId.equals(that.accessFilterGroupId)
        : that.accessFilterGroupId != null)
      return false;


    if (editAccess != that.editAccess)
      return false;


    if (priority != that.priority)
      return false;


    if (levelAccess != that.levelAccess)
      return false;


    if (levelValue != null ? !levelValue.equals(that.levelValue) : that.levelValue != null)
      return false;

    return true;
  }

  /** {@inheritDoc} **/
  @Override
  public int hashCode() {
    int res = id.hashCode();

    res = 31 * res + (name != null ? name.hashCode() : 0);

    res = 31 * res + (companyId != null ? companyId.hashCode() : 0);

    res = 31 * res + (classId != null ? classId.hashCode() : 0);

    res = 31 * res + (accessFilterGroupId != null ? accessFilterGroupId.hashCode() : 0);

    res = 31 * res + (int) editAccess;

    res = 31 * res + (priority);

    res = 31 * res + (int) levelAccess;

    res = 31 * res + (levelValue != null ? levelValue.hashCode() : 0);

    return res;
  }

  /** {@inheritDoc} **/
  @Override
  public String toString() {
    return "ClassAccessRule [" + "id=" + id + ", " + "name=" + name + ", " + "companyId="
        + companyId + ", " + "classId=" + classId + ", " + "accessFilterGroupId="
        + accessFilterGroupId + ", " + "editAccess=" + editAccess + ", " + "priority=" + priority
        + ", " + "levelAccess=" + levelAccess + ", " + "levelValue=" + levelValue + "]";
  }
}
